### ISSUE TITLE
ytmusic backend {"message":"bad request"}

### ISSUE THREAD

**Issue by skgupta507** [seeker710/ytmusic-backend#1]
after merging the files with the frontend and creating the .env files and entering the API details i seem to get error message {"message":"bad request"} how to fix this issue

**Comment by seeker710** [comment]
1. Please check the name of file in `dotenv.config({path: 'file_name'})`. In this case, .env file is named as config.env in index.js file. 
2. Change _backend url_ in the frontend files if you are testing locally. You have to make changes in this frontend files:
src -> pages -> Homepage.jsx
src -> pages -> Playerpage.jsx
src -> pages -> Searchpage.jsx
src -> components -> searchpage-components -> ResultCard.jsx
src -> components -> searchpage-components -> TopResult.jsx

**Comment by skgupta507** [comment]
Hi there, 
I did as u said iam deploying it to vercel and I updated all the links from rapid api site about the api links. The issue about bad request is fixed but now I have run into an other problem that is the homepage keeps only loading screen. The site loads but the music is not being loaded is it a api issue or some issue in the code. 
I will attach the github repository pls check it and point out the issue. The same thing is happening in the webpage u have deployed. 
https://github.com/skgupta507/music-youtube/

**Comment by seeker710** [comment]
I visited my website and homepage keeps showing loading screen with status code 400 and json `{ error: 'unsuccessful' }` in console. The problem is that api I am using have 500 request/month hard limit. So the limit was finished on current api key. That's why it was showing loading screen.
I visited your website and you are also facing error. So you also might have reached the api limit for the given key. Try to change api key for both front-end and back-end. That might solve the issue.
API Link: [https://rapidapi.com/Glavier/api/spotify23](https://rapidapi.com/Glavier/api/spotify23)
Also, the `{"message":"bad request"}` was due to invalid route request to backend. Check _index.js_ file of backend.
![image](https://github.com/seeker710/ytmusic-backend/assets/115873710/2d71f2b9-14ae-4283-8510-bdfc26db12af)
Also, as api used in this project is _freemium_. So, you have to select the $0 plan first. Don't worry, it won't ask for any card details. First, subscribe then use the api. 
Happy coding.
